<a href="https://colab.research.google.com/github/ishika-dattatray-date/python-basic-project/blob/main/special_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving countries-1.csv to countries-1.csv

In [4]:
import pandas as pd

df = pd.read_csv("countries-1.csv")

In [5]:
df.head()

   Country      Continent           Capital  Population  Area_km2
0    India           Asia         New Delhi  1428000000   3287263
1      USA  North America  Washington, D.C.   339000000   9833520
2   Brazil  South America          Brasilia   203000000   8515767
3   Canada  North America            Ottawa    41000000   9984670
4  Germany         Europe            Berlin    84000000    357022

In [6]:
df.tail()

      Country Continent                    Capital  Population  Area_km2
15      Nepal      Asia                  Kathmandu    31000000    147516
16     Bhutan      Asia                    Thimphu      790000     38394
17  Sri Lanka      Asia  Sri Jayawardenepura Kotte    22000000     65610
18         UK    Europe                     London    69000000    243610
19        UAE      Asia                  Abu Dhabi    10000000     83600

In [7]:
df.shape

(20, 5)

In [8]:
df.columns

Index(['Country', 'Continent', 'Capital', 'Population', 'Area_km2'], dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Country     20 non-null     object
 1   Continent   20 non-null     object
 2   Capital     20 non-null     object
 3   Population  20 non-null     int64
 4   Area_km2    20 non-null     int64
dtypes: int64(2), object(3)
memory usage: 932.0+ bytes

In [10]:
df.describe()

         Population      Area_km2
count  2.000000e+01  2.000000e+01
mean   2.205395e+08  3.757174e+06
std    4.171410e+08  4.898187e+06
min    7.900000e+05  3.839400e+04
25%    3.850000e+07  2.869075e+05
50%    6.850000e+07  1.111744e+06
75%    1.327500e+08  7.897960e+06
max    1.428000e+09  1.709825e+07

In [11]:
df.dtypes

Country       object
Continent     object
Capital       object
Population     int64
Area_km2       int64
dtype: object

In [12]:
df.isnull().sum()

Country       0
Continent     0
Capital       0
Population    0
Area_km2      0
dtype: int64

In [13]:
df.nunique()

Country       20
Continent      7
Capital       20
Population    20
Area_km2      20
dtype: int64

In [14]:
df.sample(5)

         Country Continent                    Capital  Population  Area_km2
17     Sri Lanka      Asia  Sri Jayawardenepura Kotte    22000000     65610
9   South Africa    Africa                   Pretoria    63000000   1221037
6          Japan      Asia                      Tokyo   123000000    377975
14         Egypt    Africa                      Cairo   114000000   1002450
5         France    Europe                      Paris    68000000    551695

In [15]:
df["Continent"].value_counts()

Continent
Asia             7
Europe           4
North America    3
South America    2
Africa           2
Oceania          1
Europe/Asia      1
Name: count, dtype: int64